### ISSUE TITLE
How to hide second module with same name

### ISSUE THREAD

**Issue by Gandohr** [eouia/MMM-AssistantMk2#132]
I have a command to show and hide every module i use.
Problem is i have 2 Calendars and they both use the same module calendar and therfore the same module name.

I use:
"HIDECALENDAR": {
    moduleExec: {
      module:(params, key)=>{
        return ["calendar"]

To select and hide/show the first, how do i select the second.
I am able to hide them one by one trough the remote module so guess it should be possible

Thanks in advance

**Comment by eouia** [comment]
It is not so easy, because As far as I know, there is no simple method to distinguish duplicated instances from one module.
There is ".identifier" property you can use. So ideally, you can use like this.
```js
"HIDECALENDAR1": {
  moduleExec: {
    module: ["calendar"],
    exec: (module, params, key) => {
        if (module.identifier == "module_1_calendar") module.hide()
     }
  }
}
```
The problems are, 
1) There is no way to assign custom identifier(like "my_1st_calendar", ) to module. The identifier would be assigned by order of modules in configurations by force. 
2) You cannot guess exact identifier because it is not opened property. And the identifier would be changed at any time by configuration modified. So, once you could have gotten "module_7_calendar" as your target calendar identifier, it could be changed when you add or remove or reorder modules in your configuration.  

I think MM should support a good way to distinguish duplicated instances.

**Comment by eouia** [comment]
If you assign `header` for each instances, you can use it for distinguishing.

```js
"HIDECALENDAR1": {
  moduleExec: {
    module: ["calendar"],
    exec: (module, params, key) => {
        if (module.data.header == "My Calendar A") module.hide()
     }
  }
}
```

**Comment by Gandohr** [comment]
This works like a charm,
thanks very much.

Bauke

On 29 Mar 2019, at 08:40, Seongnoh Sean Yi <notifications@github.com<mailto:notifications@github.com>> wrote:


If you assign header for each instances, you can use it for distinguishing.

"HIDECALENDAR1": {
  moduleExec: {
    module: ["calendar"],
    exec: (module, params, key) => {
        if (module.data.header == "My Calendar A") module.hide()
     }
  }
}
