### ISSUE TITLE
Webpage not opening

### ISSUE THREAD

**Issue by ruhulayaan** [eouia/MMM-AssistantMk2#133]
Is their a way to open webpage, when i search for something. When i search for something it just shows the url , but then exits instead of opening the said url.

**Comment by eouia** [comment]
Possible. 
But the problem is, You cannot control(scroll or close) the page opened.  
Does your mirror have a touchscreen or a mouse? Maybe you might have, but most users don't. They cannot control opened page. This visual screen response is designed for specific devices(Smart TV or Lenovo screen) which has touch screen or additional controller. 
(Anyway, if you have touchscreen, you can open that page by click the link...)

That's why I haven't provided it. If there be any good module to display web page, I can add that feature but no good module I've found.

Maybe someday I make that feature by myself. But cannot guarantee.

**Comment by eouia** [comment]
However, you might get the search result also on your Assistant App of your smart phone. You can see the page on your smartphone. Frankly said, that would be more convenient than the mirror. (Your mirror is not an alternative with your PC or smartphone. Mirror is somewhat limited device.)

**Comment by ruhulayaan** [comment]
Thanks , i also get this error on dev console when i open any youtube video. Video works well but then what does this error mean and how to fix it
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:8080').

**Comment by eouia** [comment]
Don't mind it. It is own error of Youtube SDK. unless playing is ok, forget the error.
