### ISSUE TITLE
audio response  unclear

### ISSUE THREAD

**Issue by sdetweil** [eouia/MMM-AssistantMk2#135]
ask As what time is it? (at 10:12 am), ,get short 'twelve' audio response..

saved generated mp3, cannot hear that manually played

**Comment by eouia** [comment]
Plz describe me more details.
Too short response is your issue? or it is not played? Or it could be played by manual but not in running MM?

**Comment by sdetweil** [comment]
i 'think' the response was chopped off.. i think I heard 'elve' for 10:12
I don't know where the audio is generated... 

smart-mirror (MMM-Hotword)
what time it is (assistant)
'elve' is audio response

**Comment by eouia** [comment]
Are you using HDMI as sound output? RPI HDMI output sometimes crop some start of stream when it is opened.

**Comment by sdetweil** [comment]
yes, hdmi on tv

**Comment by eouia** [comment]
That was somewhat compromised problems. 
Ver 1.x I used output stream directly to speaker(including HDMI) and sound device is always opened and connected to module, so there was no problem like this.
But the occupation of speaker device makes ppl to have a problem with multi-sound outputs. So I changed it in Ver 2.x to use recorded MP3/WAV file. Now it is not always connected. When connection is needed to output sound, it is connected. But that makes this HDMI opening issue due to new connection.
I'm researching how to solve it, but not so good idea I have yet.

**Comment by vipenm** [comment]
> That was somewhat compromised problems.
> Ver 1.x I used output stream directly to speaker(including HDMI) and sound device is always opened and connected to module, so there was no problem like this.
> But the occupation of speaker device makes ppl to have a problem with multi-sound outputs. So I changed it in Ver 2.x to use recorded MP3/WAV file. Now it is not always connected. When connection is needed to output sound, it is connected. But that makes this HDMI opening issue due to new connection.
> I'm researching how to solve it, but not so good idea I have yet.

Is it possible/recommended to downgrade for the time being while this is still an issue as the only audio out I have is the Assistant? I want to minimise on costs and wires so would prefer the audio to come through my monitor. Also, is it not possible to open a connection to the HDMI and add a delay to the response so that it doesn't get cut off?

**Comment by eouia** [comment]
Maybe possible, but in that case, other sound output(by example, raspotify, if someone might be using) could be prevented by device occupation. so i think its not so good approach.

**Comment by eouia** [comment]
I'll close this issue anyway. When I find a new stuff about this issue, it will be noticed.

**Comment by daheefman** [comment]
I was able to fix this by running
`vcgencmd force_audio hdmi 1`
