### ISSUE TITLE
Assistant electron version should be same as base MM...

### ISSUE THREAD

**Issue by sdetweil** [eouia/MMM-AssistantMk2#137]
trying to install Assistant on MM with Electron 3.0.13 , and Assistant set to 4.0.4 is near impossible..

why does Assistant need own copy of electron?

**Comment by eouia** [comment]
Not exactly.
Electron has its own Javascript Engine(>V8), it is usually different with current your system. So, on execution of electron, Electron will call some node modules(usually composed with binary) but failed due to its version different. That is why `electron-rebuild` is needed. 
If you are using `Chromium` as front-end, modules don't need to prepare dedicated binary for electron.

**Comment by sdetweil** [comment]
electron-rebuild failed on my odroird with 4.0.4 , worked ok with 3.0.13 same as MM)

**Comment by eouia** [comment]
I'll close this issue. Wish a good luck.
