### ISSUE TITLE
No audio from youtube video

### ISSUE THREAD

**Issue by bastos5** [eouia/MMM-AssistantMk2#153]
Hello, reallly thanks for you work!!

Well, when i launch a youtube video from the assistant, i have the video that run normally but i dont have sound from the Video. (BTW i have sound from the assistant).

Anyone has an idea ?

thanks a lot,
Bastos5

**Environment:**
 - Device : [RPI 3b+]
 - OS: [Raspbian Stretch]
 -

**Comment by eouia** [comment]
I think it's due to ALSA mixer issue. I'm not that kind of expert about ALSA configuration. Anyway, your ALSA configuration might send sound to speaker from only one source at once. I've heard there be ALSA mixer to mix multi-source stream at same time, but I have no idea about it. 
Anyway, I'll deprecate some dependency issue to avoid this kind of problem on next version. The next update will use default HTML5 audio instead using extern sound player program. I think it could be solved at that time without any headache H/W configuration.

**Comment by bastos5** [comment]
Thank you for you quick answer :) . i will chech Alsamixer tomorow and/or wait for you upddate.
Btw can I automate the update of assistant mk2 ?
