### ISSUE TITLE
AssistantMK2 cuts off the end of the voice response

### ISSUE THREAD

**Issue by ivanovd** [eouia/MMM-AssistantMk2#161]
I don't know if this is related, but since I started using Hotword 2.0 the Assistant cuts off the last part of the voice response.

A demo video: https://www.youtube.com/watch?v=BAfCsaXPb6w

**Comment by eouia** [comment]
I know this issue already, but unfortunately, it will be solved on next updates. (Major version change to 3.0) Plz wait for a while.

Or you can modify source to give a delay to wait finishing response.

**Comment by donn86y** [comment]
how to modify source ???

**Comment by eouia** [comment]
Not so easy. First, this bug is not common, so I cannot represent this on my devices. So hard to figure out proper solution.

1) Check the response recording file. When Assistant to start to speak response, stop the MM. You can find some .mp3 file on `tmp` directory of module. Play it and check whether it is broken or cut off. (After response spoken, the file would be removed, so you should stop before response ends)

2) If .mp3 has no issue, Change your mp3 player program. Default would be `mpg321` but on some devices, it might not work nicely. See the installation documents and modify config to use other program.

3) When changing mp3 program couldn't solve the issue, finally modify the source.
https://github.com/eouia/MMM-AssistantMk2/blob/859d27622e71ef8005e0aa31f93592eadfb2fdd6/node_helper.js#L35-L36

Change it to 
```js
setTimeout(()=>{
      this.sendSocketNotification("SPEAKER_OFF")
      cb()
}, 2000)
```
I hope this could work, but if not so, Your environment might have something missing or wrong. I cannot do anything at that case.

**Comment by donn86y** [comment]
Thanks for reply none of those options worked for me should i start over
from scratch??

**Comment by eouia** [comment]
???
1) Is the mp3 file broken? We should start from this point. If mp3 file is not broken, your sound environment or audio-play program might not be fit with this module.
2) Which mp3 player program did you test? On some envrionment, `mpg321` could not be installed properly. You can test other program like mplayer or mpg123 (Of course, you need to install them if they are not installed yet)
2-1) Some speaker - especially HDMI - could lost some data.  So worthy to try other speaker.

Frankly said, the 3) wouldn't be a help if there be an issue on 1~2.

**Comment by daheefman** [comment]
I was able to fix this by running
`vcgencmd force_audio hdmi 1`

**Comment by ivanovd** [comment]
I was already outputting that to hdmi, so I fixed it by installing and switching to mpg123
