### ISSUE TITLE
Problem with youtube

### ISSUE THREAD

**Issue by BabbyBabby** [eouia/MMM-AssistantMk2#178]
Even after entering " youtubeAutoplay: true, "
calling a video on youtube, sometimes the videos start and sometimes not
Is it just my problem?

Theese are the warning:
1)  /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:127 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
    protocols.This exposes users of this app to unnecessary security risks.

2) Unrecognized feature: 'picture-in-picture'.
MMM-AssistantMk2.js:744 Youtube player: on ready.
MMM-AssistantMk2.js:782 youtube status: -1
MMM-AssistantMk2.js:782 youtube status: 3
MMM-AssistantMk2.js:782 youtube status: -1
﻿
thanks

**Comment by eouia** [comment]
Sorry for late reply.
Those 2 kinds of errors or messages(electron security & pip ) are not related with real performance.

status :3 -> status :-1 means, API was trying your video loading but failed. In many case it is due to wrong id of video(removed or blocked) or no permission to play outside of youtube (by owner or youtube)
