### ISSUE TITLE
Cant hear assistants voice on basic commands

### ISSUE THREAD

**Issue by Kube01** [eouia/MMM-AssistantMk2#235]
Hi eouia,
I have installed Mk2 as followed from your instructions everything works except the output, when I ask the assistant to "tell me the time" or "whats the weather like" it just shows me the web search without actually replying with her voice. However when i ask her to play something from youtube it say "heres what i found on the web" and starts playing the video with no problem, However i can't stop it with the same hotword which is "smart mirror". I have double checked the MMM-AssistantMk2.js file but i cant find anything that could cause this.
    responseVoice: true, // If available, Assistant will response with her voice.
    responseScreen: true, // If available, Assistant will response with some rendered HTML
    responseAlert: true, // If available, Assistant will response with Alert module of MM
I also have a similar problem with MMM-Spotify where i cant hear the music from the speakers.
I am using a Voice HAT KIT 

Sorry if the error is obvious im a newbie if it comes to things like this

	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
{
  module: "MMM-Spotify",
  position: "bottom_left",
  config: {
    style: "mini", // "default" or "mini" available
    control: "default", //"default", "hidden" available
    updateInterval: 1000,
    onStart: null, // disable onStart feature with `null`
    allowDevices: [], //If you want to limit devices to display info, use this.
    // allowDevices: ["RASPOTIFY", "My iPhoneX", "My Home speaker"],
  } 
},
                {
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {
    record: {
      recordProgram : "arecord",  
      device        : "plughw:0",
    },

    notifications: {
      ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
      ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
    },
    }
},
{
  module: "MMM-Hotword",
  position: "top_right",
  config: {
    chimeOnFinish:null,
    mic: {
      recordProgram : "arecord",  
      device        : "plughw:0",
    },
    models: [
      {
        hotwords    : "smart_mirror",
        file        : "smart_mirror.umdl",
        sensitivity : "0.5",
      },
    ],
    defaultCommand: {
      notificationExec: {
        notification: "ASSISTANT_ACTIVATE",
        payload: (detected, afterRecord) => {
          return {profile:"default"}
        }
      },
      afterRecordLimit:0,
      restart:false,
    },
  },
},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by Kube01** [comment]
*UPDATE* it managed to fix it self somehow ? 
However, when the music is playing from spotify and i call out the hotword the music stops and the mk2 assistant freezes and i cant resume the music as it stops playing

**Comment by eouia** [comment]
VOICE HAT... 
That seems the reason for all your problem.
I haven't used it, but as far as I know, VOICE HAT is a kind of thing which has Mic and Speaker together in one kit. right?
I think you've set ALSA to assign your voice HAT as device:0 for both mic and speaker . Usually, it would be no problem at all in common usual usage. People can record and play turn-by-turn.
But in this module, works like this;
1. Mic finish to listen to your voice
2. cut the Mic
3. Open the speaker
4. Stream the output>
The problem is, step 2 and step 3 happen sequentially, but by physical limitation, cutting the mic would take some time. (not predictable).
Ususally, in the normal environment - separated Mic and speaker which have different device name - this would not be an issue.
But in this kind of VOICE HAT, when the same device name is assigned to both mic and speaker, this could be an issue. Step 2(cutting device 0) could be finished after step 3(open device 0), that will make re-closing device.

The solution would be;
- Give different device name to mic and speaker. modify configuration by them.

Sorry, I'm not that kind of expert so cannot give you exact instruction or example of ALSA.

**Comment by Kube01** [comment]
Thanks a lot for the quick reply, I will try your advice or just get a completely seperate mic and speakers :)
