### ISSUE TITLE
Delete between request and command

### ISSUE THREAD

**Issue by defiantlibra** [eouia/MMM-AssistantMk2#265]
Hi, I have installed version 3 of assistant and the latest version of hotword but I am continuing to have a strange error .. in practice between my request and the command there is a delay of about 5 seconds. for example .. if I say "jarvis how are you" after about 5 seconds he replies "i'm fine thanks". i have a raspberry pi3b + and with version 2 of the assistant everything worked very fast. What can be the error?

**Comment by eouia** [comment]
How backend log says? Show me the log when it happens.
There could be 2 suspicious points.

1) `afterRecord` related.
How did you speak `Jarvis How are you`?
In ver 3, with new MMM-Hotword, AMK2 can understand `seamless query with hotword`.

In ver 2, you might use like this; `Jarvis (Hotword recognized then wait to activate AMK2 with beep), How are you?`.
In ver 3, you can use also like this; `Jarvis How are you?` (without any pause).  After some seconds of full spoken, Hotword and AMK2 each can understand hotword and query separately. It is more convenient. But the only issue is, it needs some seconds to detect end of your spoken phrase (but not too long. 1~2 secs)

2) retry with transcription fails.
I added a retrial feature when your spoken transcription was failed to be recognized. Sometimes Google fails to understand your spoken. It could be somehow transcripted but not completed. 
In ver2, it could make some error. 
In ver3, my module retry with `current transcripted text - not perfect but understandable` instead of your failed voice audio. It could takes somewhat seconds.

Anyway, I need a log to diagnose details.

**Comment by defiantlibra** [comment]
as soon as I can I attach a log file. in any case, when I close the magic mirror with ctrl q does "AfterRecords: 4000" appear? what is this value? can i decrese?

**Comment by eouia** [comment]
`AfterRecords: 4000` means, your mic is listening after hotword. 4000 is byte chunk currently listening. Audio is very huge data-type, so it needs to be chunked to handle. Not weird thing.

**Comment by eouia** [comment]
If your environment is somewhat noisy, My module cannot distinguish the end of your phrase precisely, in that case, it will continue to listen maximum 7 seconds and cut the audio then use it. 
https://github.com/eouia/MMM-Hotword/blob/a56ca25aca4f6ba8888383377ca729ce5f3a4bd8/recipes/with-AMk2v3_Jarvis.js#L26

**Comment by eouia** [comment]
You can set `afterRecordLimit:0` in Hotword recipe. In that case, you cannot use `seamless query` but able to use V2 style - `Hotword (pause and beep) blah blah`

**Comment by eouia** [comment]
Or my colleague @bugsounet will update recipe for noisy environment soon. :)

**Comment by defiantlibra** [comment]
YOU ARE THE BEST.
i have decrese the value from 7 to 2 and now it works perfect. thank you so much!!

**Comment by eouia** [comment]
Sounds so nice.

**Comment by bugsounet** [comment]
hi, I make a new recipe for noisy enviromement to correct this isssue
I will push it as soon as possible :)
